# Generated by Django 2.2.13 on 2021-08-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='user',
            new_name='username',
        ),
    ]
