# Generated by Django 2.2.13 on 2021-08-28 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210828_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='username',
            new_name='user',
        ),
    ]
