# Generated by Django 3.2.6 on 2024-01-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210828_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='Time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='user',
            new_name='username',
        ),
        migrations.AddField(
            model_name='data',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
