# Generated by Django 3.2.6 on 2024-01-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20240113_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='join date'),
        ),
        migrations.AlterField(
            model_name='data',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last login'),
        ),
    ]
